language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-5.1.x

matrix:
  exclude:
    # has test/unit/testcase removed, and also 3.2.x is too old to support
    # ruby 2.2.0. so ignoring this combination.
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-3.2.x
    # rack with rails 5 cannot be installed in ruby versions prior to 2.2.2
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5.1.x

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script:
  - bundle exec rake --trace
